// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
